### ISSUE TITLE
Release new gem version?

### ISSUE THREAD

**Issue by timsutton** [arangamani/jenkins_api_client#304]
It seems like are significant changes in master since the last release, which was years ago. Would it be possible to cut a new gem version based on the current state of master?

**Comment by ninp0** [comment]
Please release a gem version compatible with ruby 3.0.0.  Thanks!

**Comment by grosser** [comment]
@arangamani 🙇

**Comment by capripot** [comment]
Do we need to add more maintainers? Looks like the gem is not maintained currently?

**Comment by grosser** [comment]
yeah

**Comment by asghaier** [comment]
Hi @capripot and @grosser ,

I was using the library myself. But since the maintainer does not seem to be active anymore I have decided to create a new gem based on this one:
https://github.com/asghaier/jenkins_api_client2

I will take it easy for now, I just made sure that it builds and runs the unit tests successfully for the latest Ruby releases.
Then I will look into open issues and PRs for this project and try to merge them in jenkins_api_client2.
I have also updated the CI pipelines to use Github Actions but still need to remove Travis CI configs later on.

I hope the original owner would add other maintainers, but I am currently using a release from 2017 and the maintainer is not responding to anything for over 3 years.

**Comment by arangamani** [comment]
@asghaier are you willing to be a maintainer of this project?

**Comment by grosser** [comment]
I'd also be willing to do some basic maintenance (merge PRs/bump versions etc) if necessary, not deep into jenkins but need the gem for a project for at least another year or so.

**Comment by arangamani** [comment]
@grosser Perfect! What email should I use for inviting you to rubygems.org?

**Comment by grosser** [comment]
michael@grosser.it

**Comment by thebravoman** [comment]
If I am able to get it with ruby-3.1.3 because of heroku push for ruby-3.1.3 I will also be using the project for a few years. 

Letting you know that I am using the master branch since 2018 and had no issues. 

First thing I tried to do is get rspec working 

```
Finished in 10.56 seconds (files took 0.81205 seconds to load)
376 examples, 115 failures, 2 errors occurred outside of examples
```

@grosser @asghaier want to join forces on this one and bring it up to ruby -> 3.1 and merge some of the prs, instead of maintaining our own forks.

**Comment by grosser** [comment]
all good now ... but functional tests are broken ...

**Comment by arangamani** [comment]
How critical are those functional tests? Can we get away with doing quick manual test for a release?

**Comment by grosser** [comment]
ah they were always broken so 🙈

**Comment by grosser** [comment]
2.0.0 🤞 
... I'll yank if it's broken ...

**Comment by grosser** [comment]
@ccouzens also volunteered to help

**Comment by arangamani** [comment]
> @ccouzens also volunteered to help

Collaborator invite sent.

**Comment by asghaier** [comment]
@arangamani @grosser you can add me as a co-maintainer if you want.
My initial goal for now is to make sure it works with ruby 3.0 and above fore at least next year or two.

**Comment by ccouzens** [comment]
> > @ccouzens also volunteered to help
> 
> Collaborator invite sent.

Thanks both.

Unfortunately I no longer have the time to be a co-maintainer of this project.

It sounds like this project has 2 good new maintainers, so I'm happy the project's future is bright. Good luck 🙂

**Comment by ashkulz** [comment]
Thanks for the release, @grosser :tada:
